apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
- name: dariushorvath/dhk-ambulance-ufe
  newName: dariushorvath/dhk-ambulance-ufe # {"$imagepolicy": "dhk-hospital:dhk-ambulance-ufe:name"}
  newTag: main # {"$imagepolicy": "dhk-hospital:dhk-ambulance-ufe:tag"}