apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dhk-hospital # chceme tieto objekty umiestniť do `wac-hospital` namespace
                         # tento zapis preťaží hodnoty "namespace" vo všetkých objektoch
labels:
- pairs:
    app.kubernetes.io/part-of: dhk-hospital

components:
- ../../../components/version-developers
- https://github.com/HorvathDarius/dhk-ambulance-webapi//deployments/kustomize/components/mongodb

resources:
- ../../../apps/dhk-ambulance-ufe
- ../../../apps/dhk-ambulance-webapi
- ../../../apps/mongo-express

patches:
- path: patches/ambulance-webapi.service.yaml
