apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: dhk-ambulance-ufe-link
spec:
  microFrontend: polyfea-md-shell # referencia na microfrontend, z ktorého sa načíta element
  element: polyfea-md-app # element, ktorý bude vložený na stránku
  attributes: # atribúty elementu polyfea-md-app
    - name: headline
      value: Personálna správa
    - name: short-headline
      value: Personálna správa
    - name: supporting-text
      value: |
        Personálna správa, prehľad o zamestnancoch nemocnice, ich priradenie k ambulanciám a nemocničným oddeleniam, prehľad o výkonoch a správa osobnej dokumentácie
    - name: material-icon
      value: people
    - name: href # presmerovanie po kliknutí na element polyfea-md-app
      value: ./dhk-ambulance-wl
  priority: 10
  displayRules: # pravidlá, kde sa má element vložiť v obálke
    - anyOf:
      - context-name: applications
      - context-name: rail-content
      - context-name: drawer-content